Yes, it's possible. Some examples are if the JVM crashes, the program
runs into a fatal error or if we explicitly interrupt the run of the
program with System.exit().

Here is an example:

public int someMethod(int i){

try{

> //some statement

> return 1;

}catch(Exception e){

> //some statement

> return 999;

}finally{

> //finally block statements

}

}

finally block will be executed irrespective of the exception or not. The
only case where finally block is not executed is when it encounters
'System.exit()' method anywhere in try/catch block.